App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('sign-up/', views.sign_up, name = 'sign_up'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('profile/', views.profile, name = 'profile'),
    path('update-profile/', views.update_profile, name = 'update_profile'),
    path('password/', views.change_password, name = 'change_password'), # This slug is default
    path('add-profile-pic/', views.add_profile_pic, name = 'add_profile_pic'),
    path('change-profile-pic/', views.change_profile_pic, name = 'change_profile_pic'),
]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name = 'index'),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to = 'profile_pics')

App_Login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label = "Email Address", required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')
        
class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

App_Login/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def sign_up(request):
    form = forms.SignUpForm()
    registered = False

    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            registered = True
        
    diction = {
        'form': form,
        'registered': registered,
    }

    return render(request, 'App_Login/sign_up.html', context=diction)

def login_page(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)

            if user is not None:
                login(request, user)

                return redirect('index')


    diction = {
        'form': form,
    }    

    return render(request, 'App_Login/login.html', context = diction)

@login_required
def logout_user(request):
    logout(request)

    return redirect('App_Login:login')   

@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})    

@login_required
def update_profile(request):
    form = forms.UserProfileChange(instance = request.user)

    if request.method == 'POST':
        form = forms.UserProfileChange(request.POST, instance = request.user)

        if form.is_valid():
            form.save(commit=True)

            return redirect('App_Login:profile')
    diction = {
        'form': form,
    }     

    return render(request, 'App_Login/update_profile.html', context=diction)

@login_required
def change_password(request):
    form = PasswordChangeForm(request.user)
    changed = False

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)

        if form.is_valid():
            form.save()
            changed =True
            
    diction = {
        'form': form,
        'changed': changed,
    }    

    return render(request, 'App_Login/change_password.html', context=diction)

@login_required
def add_profile_pic(request):
    form = forms.ProfilePic()

    if request.method == 'POST':
        form = forms.ProfilePic(request.POST, request.FILES)

        if form.is_valid():
            user_prof = form.save(commit=False)
            user_prof.user = request.user

            user_prof.save()

            return redirect('App_Login:profile')
    diction = {
        'form': form
    }

    return render(request, 'App_Login/add_profile_pic.html', context = diction)

@login_required
def change_profile_pic(request):
    form = forms.ProfilePic(instance=request.user.user_profile)

    if request.method == 'POST':
        form = forms.ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)

        if form.is_valid():
            form.save(commit=True)

            return redirect('App_Login:profile')
    diction = {
        'form': form,
    }

    return render(request, 'App_Login/change_profile_pic.html', context=diction)

templates/App_Login/add_profile_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Profile Picture{% endblock title %}

{% block content %}
<h2>Add Your Profile Pic</h2>

<form method = 'POST' enctype = "multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <br>
    <button type = "submit" class = "btn btn-primary btn-sm">Add Picture</button>
</form>
{% endblock content %}

templates/App_Login/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Change Password{% endblock title %}

{% block content %}
    <h2>Change Your Password</h2>

    {% if changed %}
        <div class = "alert alert-success">
            Password Changed Successfully!
        </div>
    {% else %}
        <form method = 'POST'>
            {{form|crispy}}
            {% csrf_token %}
            <br>
            <button type = "submit" class = "btn btn-primary btn-sm">Change</button>
        </form>
    {% endif %}
{% endblock content %}

templates/App_Login/change_profile_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update Profile Picture{% endblock title %}

{% block content %}
<h2>Change Your Profile Pic</h2>

<form method = 'POST' enctype = "multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <br>
    <button type = "submit" class = "btn btn-primary btn-sm">Change Picture</button>
</form>
{% endblock content %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock title %}

{% block content %}
    <h2>Login Into Your Account</h2>

    <form method = 'POST'>
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <button type = "submit" class = "btn btn-primary btn-sm">Login</button>
    </form>
{% endblock content %}

templates/App_Login/profile.html
{% extends 'base.html' %}

{% block title %}Profile Page{% endblock title %}

{% block content %}
    <h2>Your Profile</h2>
    {% if user.user_profile %}
        <img src="{{user.user_profile.profile_pic.url}}" class = "rounded-circle" width = "120px">
        <br>
        <br>
        <a href = "{% url 'App_Login:change_profile_pic' %}" class = "btn btn-info btn-sm">Change Profile Pic</a>
    {% else %}
        <img src = "/media/profile_pics/default.jpg" class = "rounded-circle" width = "120px">
        <br>
        <br>

        <a href = "{% url 'App_Login:add_profile_pic' %}" class = "btn btn-info btn-sm">Add Profile Pic</a>
    {% endif %}
    <br>
    <br>
    <p>Username: {{user.username}}</p>
    <p>Email: {{user.email}}</p>
    <p>Name: {{user.first_name}} {{user.last_name}}</p>

    <br>

    <a href = "{% url 'App_Login:update_profile' %}" class = "btn btn-warning btn-sm">Change Profile Info</a>
{% endblock content %}

templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}SignUp{% endblock title %}

{% block content %}
    {% if registered %}
        <div class = "alert alert-success">
            Account Created Successfully! <a href = "{% url 'App_Login:login' %}">Login Here</a>
        </div>
    {% else %}    
    
        <h2> Create New Account</h2>

        <form method = 'POST'>
            {{form|crispy}}
            {% csrf_token %}
            <button type = "submit" class = "btn btn-success btn-sm">Create Account</button>
        </form>
        <br>
        <p>Already have an account? <a href = "{% url 'App_Login:login' %}">Login here.</a></p>
    {% endif %}
{% endblock content %}

templates/App_Login/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Change Profile{% endblock title %}

{% block content %}
    <h2>Update Your Profile</h2>

    <form method = 'POST'>
        {{form|crispy}}
        {% csrf_token %}
         <button type = "submit" class = "btn btn-primary btn-sm">Update</button>
    </form>
{% endblock content %}