App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.blog_list, name = 'blog_list'),
    path('create-blog/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('blog-details/<slug:slug>/', views.blog_details, name = 'blog_details'),
    path('like/<pk>', views.like, name = 'like'),
    path('unlike/<pk>', views.unlike, name = 'unlike'),
    path('my-blogs/', views.MyBlogs.as_view(), name = 'my_blogs'),
    path('edit-blog/<pk>', views.EditBlog.as_view(), name = 'edit_blog')
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('sign-up/', views.sign_up, name = 'sign_up'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('profile/', views.profile, name = 'profile'),
    path('update-profile/', views.update_profile, name = 'update_profile'),
    path('password/', views.change_password, name = 'change_password'), # This slug is default
    path('add-profile-pic/', views.add_profile_pic, name = 'add_profile_pic'),
    path('change-profile-pic/', views.change_profile_pic, name = 'change_profile_pic'),
]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name = 'index'),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    
    <nav class = "navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class = "navbar-nav">
            <li class = "nav-item active">
                <a class = "nav-link" href = "{% url 'index' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class = "nav-item active">
                <a class = "nav-link" href = "{% url 'App_Blog:create_blog' %}">Create Blog</a>
              </li>
              <li class = "nav-item active">
                <a class = "nav-link" href = "{% url 'App_Login:logout' %}">Logout</a>
              </li>
              <li class = "nav-item active">
                <a class = "nav-link" href = "{% url 'App_Login:profile' %}">Profile</a>
              </li>
            {% else %}
              <li class = "nav-item active">
                <a class = "nav-link" href = "{% url 'App_Login:sign_up' %}">SignUp</a>
              </li>
              <li class = "nav-item active">
                <a class = "nav-link" href = "{% url 'App_Login:login' %}">Login</a>
              </li>
            {% endif %}
            
            
        </ul>
        
        {% if user.is_authenticated %}
         <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown" >
            {{user.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a></li>
            <li><a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a></li>
          </ul>
        </div>
        {% endif %}
    </nav>

    <div class = "container" style = "padding-top:20px">

    {% block content %}{% endblock content %}

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script> {% endcomment %}
    
  </body>
</html>