App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.blog_list, name = 'blog_list'),
    path('create-blog/', views.CreateBlog.as_view(), name = 'create_blog'),
    path('blog-details/<slug:slug>/', views.blog_details, name = 'blog_details'),
    path('like/<pk>', views.like, name = 'like'),
    path('unlike/<pk>', views.unlike, name = 'unlike'),
    path('my-blogs/', views.MyBlogs.as_view(), name = 'my_blogs'),
    path('edit-blog/<pk>', views.EditBlog.as_view(), name = 'edit_blog')
]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name = 'index'),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=420, verbose_name='Put a title')
    slug = models.SlugField(max_length=420, unique=True)
    blog_content = models.TextField(verbose_name='What is on your mind?')
    blog_image = models.ImageField(upload_to = 'blog_images', verbose_name='Blog Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name='blog_comment', on_delete=models.CASCADE)        
    user = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    # Other way of ordering directly in models.
    class Meta:
        ordering = ['-comment_date']

    def __str__(self):
        return self.comment   

class Like(models.Model):
    blog = models.ForeignKey(Blog, related_name='liked_blog', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='liker_user', on_delete=models.CASCADE)

App_Blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, TemplateView
from .models import Blog, Comment, Like
from django.contrib.auth.decorators import login_required

# Login required for class based view
from django.contrib.auth.mixins import LoginRequiredMixin 
import uuid 
from . import forms
from django.urls import reverse_lazy

# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all().order_by('-publish_date')

    return render(request, 'App_Blog/blog_list.html', context={'blogs': blogs})

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image')

    def form_valid(self, form): # This function name is default.
        blog_obj = form.save(commit = False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4()) # Change all spaces with '-' .... sanyam-garg-id
        blog_obj.save()
        
        return redirect('index')

def blog_details(request, slug):
    blog = Blog.objects.get(slug = slug)
    comment = forms.CommentForm()
    liked = Like.objects.filter(blog=blog, user=request.user)

    if liked:
        already_liked = True
    else:
        already_liked = False    

    if request.method == 'POST':
        comment = forms.CommentForm(request.POST)

        if comment.is_valid():
            comment_final = comment.save(commit=False)
            comment_final.user = request.user
            comment_final.blog = blog
            comment_final.save()

            return redirect('App_Blog:blog_details', slug = slug)

    diction = {
        'blog': blog,
        'comment': comment,
        'already_liked': already_liked,
    }

    return render(request, 'App_Blog/blog_details.html', context=diction)

@login_required
def like(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog = blog, user = user) # Objects(Likes) with the corressponding user and blog.

    if not already_liked: # If such a like does not exist
        liked_blog = Like(blog = blog, user=user) # Liking it
        liked_blog.save()

        return redirect('App_Blog:blog_details', slug=blog.slug)

@login_required
def unlike(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)

    if already_liked: # If such a like exists
        already_liked.delete()

    return redirect('App_Blog:blog_details', slug=blog.slug)

class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'

class EditBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    template_name = 'App_Blog/edit_blog.html' 
    fields = ('blog_title', 'blog_content', 'blog_image') 
    context_object_name = 'blog'

    def get_success_url(self, **kwargs): # After everything is done.
        return reverse_lazy('App_Blog:blog_details', kwargs = {'slug': self.object.slug})  # Use ONLY reverse_lazy here

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Blog Details{% endblock title %}

{% block content %}
<div class = "row">
    <div class = "col-sm-6">
        <h2>{{blog.blog_title}}</h2>
        <h4><b>Posted By:</b> {{blog.author}}</h4>
        <i><h6>Published On: {{blog.publish_date}}</h6></i>
        <i><h6>Updated On: {{blog.update_date}}</h6></i>
        <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
    </div>

    <div class = "col-sm-6">
        <img src = "{{blog.blog_image.url}}" width = "100%">
    </div>

    {{blog.blog_content|linebreaks}}

</div>

<hr>
{% if not already_liked %}
<a href = "{% url 'App_Blog:like' pk=blog.pk %}">
    <i class = "fa fa-thumbs-o-up fa-2x"></i>
</a>
{% else %}
<a href = "{% url 'App_Blog:unlike' pk=blog.pk %}">
    <i class = "fa fa-thumbs-o-down fa-2x"></i>
</a>
{% endif %}

<div class = "row">
    <div class = "col-sm-6">
        <h5>Comments:</h5>
        {% for comment in blog.blog_comment.all %}
        <p><a href = '#'>{{comment.user}}</a></p>
        <b>{{comment.comment}}</b><br>
        <h6><i>{{comment.comment_date}}</i></h6>
        {% endfor %}
    </div>

    <div class = "col-sm-6">
        <form method = 'POST'>
            {{comment|crispy}}
            {% csrf_token %}
            <br>
            <button type = "submit" class = "btn btn-primary btn-sm">Add Comment</button>
        </form>
    </div>
</div>

{% endblock content %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Home{% endblock title %}

{% block content %}

    {% for blog in blogs %}
        <h2>{{blog.blog_title}}</h2>
        <h6><i>{{blog.publish_date}}</i></h6>

        <div class = "row">
            <div class = "col-sm-4">
                <img src = "{{blog.blog_image.url}}" alt = "{{blog.blog_title}}" title = "{{blog.blog_title}}" width = "100%">
            </div>

            <div class = "col-sm-8">
                <p>{{blog.blog_content|range_filter|linebreaks}}
                    <a href = "{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
                </p>
                <h6><b>Posted By:</b> <a href = "#">{{blog.author}}</a></h6>
                <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create Blog{% endblock title %}

{% block content %}
    <h2>Write Your Blog Here</h2>

    <form method = 'POST' enctype = "multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <br><br>
        <button type = "submit" class = "btn btn-success btn-sm">Publish</button>
    </form>
{% endblock content %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit Blog{% endblock title %}

{% block content %}
{% if blog.author == user %}
    <form method = 'POST' enctype = "multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class = "btn btn-info btn-sm">Edit</button>
    </form>
{% else %}
<p> You are not allowed to view this page.</p>    
{% endif %}    
{% endblock content %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}My Blogs{% endblock title %}

{% block content %}
    {% for blog in user.post_author.all %}
        <h2>{{blog.blog_title}}</h2>
        <h6><i>{{blog.publish_date}}</i></h6>

        <div class = "row">
            <div class = "col-sm-4">
                <img src = "{{blog.blog_image.url}}" alt = "{{blog.blog_title}}" title = "{{blog.blog_title}}" width = "100%">
            </div>

            <div class = "col-sm-8">
                <p>{{blog.blog_content|range_filter|linebreaks}}
                    <a href = "{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
                </p>
                <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
            </div>
        </div>
        <br>
        <a href = "{% url 'App_Blog:edit_blog' pk=blog.pk%}" class = "btn btn-info btn-sm">Edit</a>
        <hr>
    {% endfor %}
{% endblock content %}